apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-preprocessing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-preprocessing
  template:
    metadata:
      labels:
        app: data-preprocessing
    spec:
      containers:
      - name: data-preprocessing-container
        image: data_preprocessing/data_preprocessing_image
---
apiVersion: v1
kind: Service
metadata:
  name: data-preprocessing-service
spec:
  selector:
    app: data-preprocessing
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
